"breaking-change": ["bc/*", "revert/*"]
"feature": feature/*
"fix": fix/*
"update": ["update/*", "refactor/*"]
"security": ["security/*", "dependabot"]
"chore": ["chore/*", "test/*, ci/*", "style/*", "docs/*"]
