categories:
   - labels:
        - "breaking-change"
     title: "Breaking Changes"
   - labels:
        - "feature"
     title: "New Features"
   - labels:
        - "fix"
     title: "Bug Fixes"
   - labels:
        - "update"
        - "security"
     title: "General Updates and Security Fixes"

change-template: "- #$NUMBER: $TITLE"
template: |

   $CHANGES
