services:
  docs:
    build:
      context: .
      target: frontend-base
    depends_on:
      - traefik

  design:
    build:
      context: .
      target: frontend-base
    depends_on:
      - traefik

  web:
    build:
      context: .
      target: frontend-base
    depends_on:
      - design

  design-storybook:
    build:
      context: .
      target: frontend-base
    depends_on:
      - design

  # API .......................................................................
  api:
    build:
      context: .
      target: base
    depends_on:
      - traefik
      - redis
      - mysql

  horizon:
    build:
      context: .
      target: base
    depends_on:
      - api

  # Infrastructure ............................................................
  traefik:
    image: traefik:v2.10

  mysql:
    image: mysql:8.2

  redis:
    image: redis:7.2
