services:
  traefik:
    image: traefik:v3.1
  # docs:
  #   build:
  #     context: .
  #     target: frontend-base
  #   depends_on:
  #     - traefik

  web:
    build:
      context: .
      target: frontend
    # depends_on:
    #   - traefik

  # design-storybook:
  #   build:
  #     context: .
  #     target: frontend-base
  #   depends_on:
  #     - design

  application:
    build:
      context: .
      target: development
    # depends_on:
      # - traefik
      # - redis
      # - mysql

  # horizon:
  #   build:
  #     context: .
  #     target: base
  #   depends_on:
  #     - app

  # Infrastructure ............................................................

  mysql:
    image: mysql:8.2

  redis:
    image: redis:7.2
