services:
  traefik:
    image: traefik:v3.1

  mysql:
    image: mysql:8.2

  redis:
    image: redis:7.2

  # docs:
  #   build:
  #     context: .
  #     target: frontend
  #     args:
  #       - WORKDIR=/platform/docs
  #       - PACKAGES=docs
  #   depends_on:
  #     - traefik

  ds:
    build:
      context: .
      target: frontend
      args:
        - WORKDIR=/platform/frontend
        - PACKAGES=frontend
    depends_on:
      - traefik
      - application

  web:
    build:
      context: .
      target: frontend
      args:
        - WORKDIR=/platform/frontend
        - PACKAGES=frontend
    depends_on:
      - traefik
      - ds

  application:
    build:
      context: .
      target: development
    depends_on:
      - traefik
      - redis
      - mysql

  horizon:
    build:
      context: .
      target: base
    depends_on:
      - redis
      - application











