version: "3"

includes:
  app:
    taskfile: ./.infrastructure/tasks/app.yml
    dir: ./application

  ds:
    taskfile: ./.infrastructure/tasks/ds.yml
    dir: ./front/ds

  docs:
    taskfile: ./.infrastructure/tasks/docs.yml
    dir: ./docs

  front:
    taskfile: ./.infrastructure/tasks/front.yml
    dir: ./front

  platform:
    taskfile: ./.infrastructure/tasks/platform.yml
    dir: ./

  web:
    taskfile: ./.infrastructure/tasks/web.yml
    dir: ./front

tasks:
  init:
    desc: Install everything and start docker
    cmds:
      - task: app:install
      - task: front:install

  update:
    desc: Update everything in one swoop
    cmds:
      - task: app:update
      - task: front:update

  clean:
    desc: Delete all dependencies and build folders and start again
    prompt: This will delete all node_modules, dist folders and vendor folders...are you sure you want to do this?
    cmds:
      - task: app:clean
      - task: app:env
      - task: design:clean
      - task: docs:clean
      - task: web:clean
      - task: front:clean
