version: "3"

includes:
  api:
    taskfile: ./.infrastructure/tasks/api.yml
    dir: ./backend

  design:
    taskfile: ./.infrastructure/tasks/design.yml
    dir: ./frontend

  docs:
    taskfile: ./.infrastructure/tasks/docs.yml
    dir: ./frontend/docs

  dev:
    taskfile: ./.infrastructure/tasks/dev.yml

  frontend:
    taskfile: ./.infrastructure/tasks/frontend.yml
    dir: ./frontend

  platform:
    taskfile: ./.infrastructure/tasks/platform.yml
    dir: ./

  web:
    taskfile: ./.infrastructure/tasks/web.yml
    dir: ./frontend

tasks:
  init:
    desc: Install everything and start docker
    cmds:
      - task: api:install
      - task: frontend:install

  update:
    desc: Update everything in one swoop
    cmds:
      - task: api:update
      - task: frontend:update

  clean:
    desc: Delete all dependencies and build folders and start again
    prompt: This will delete all node_modules, dist folders and vendor folders...are you sure you want to do this?
    cmds:
      - task: api:clean
      - task: design:clean
      - task: docs:clean
      - task: web:clean
      - task: frontend:clean
