version: "3"

includes:
   app:
      taskfile: ./.infrastructure/tasks/app.yml
      dir: ./application

   docs:
      taskfile: ./.infrastructure/tasks/docs.yml
      dir: ./docs

   front:
      taskfile: ./.infrastructure/tasks/front.yml
      dir: ./frontend

   platform:
      taskfile: ./.infrastructure/tasks/platform.yml
      dir: ./

tasks:
   env:
      desc: Update all .env and generated stub files
      dir: ./application
      cmds:
         - php artisan generate:env

   init:
      desc: Install everything and start docker
      cmds:
         - task: env
         - task: app:install
         - task: front:install

   update:
      desc: Update everything in one swoop
      cmds:
         - task: app:update
         - task: front:update

   start:
      cmds:
         - task: platform:start
         - task: front:start
