version: "3"

includes:
   app:
      taskfile: ./.infrastructure/tasks/app.yml
      dir: ./application

   docs:
      taskfile: ./.infrastructure/tasks/docs.yml
      dir: ./docs

   front:
      taskfile: ./.infrastructure/tasks/front.yml
      dir: ./frontend

   platform:
      taskfile: ./.infrastructure/tasks/platform.yml
      dir: ./

tasks:
   init:
      desc: Install everything and start docker
      cmds:
         - task: app:install
         - task: front:install

   update:
      desc: Update everything in one swoop
      cmds:
         - task: app:update
         - task: front:update
