CREATE DATABASE IF NOT EXISTS platform_backend;

GRANT DELETE, EXECUTE, SELECT, INDEX, DROP, CREATE ROUTINE, TRIGGER, CREATE TEMPORARY TABLES, ALTER ROUTINE, INSERT, REFERENCES, CREATE VIEW, SHOW VIEW, ALTER, UPDATE, EVENT, LOCK TABLES, CREATE ON `platform_backend_pulse`.* TO 'mysqluser'@'%';

FLUSH PRIVILEGES;
