version: "3"

tasks:
  install:
    desc: Install all the packages for the backend
    cmds:
      - composer install

  clean:
    desc: Flush all the dependencies
    cmds:
      - rm -Rf vendor

  dump:
    desc: A composer dump
    cmds:
      - composer du

  format:
    desc: Formats laravel code with Pint
    cmds:
      - pint

  lint:
    disc: Runs PHPStan over backend
    cmds:
      - ./vendor/bin/phpstan analyse --memory-limit=2G

  migrate:
    desc: Run database migrations
    cmds:
      - php artisan migrate

  seed:
    desc: Run database seeders
    cmds:
      - php artisan db:seed

  test:
    desc: Run all the tests
    cmds:
      - task: test-unit
      - task: test-feature
      - task: test-architecture

  test-unit:
    desc: Run all the unit tests
    cmds:
      - echo "Unit Tests"

  test-feature:
    desc: Run all the feature tests
    cmds:
      - echo "Feature Tests"

  test-architecture:
    desc: Run all the architecture tests
    cmds:
      - echo "Architecture Tests"

  update:
    desc: Update laravel dependencies
    cmds:
      - composer update
