version: "3"

tasks:
   clean:
      desc: Flush all the dependencies
      cmds:
         - rm -Rf vendor

   dump:
      desc: A composer dump
      cmds:
         - composer du

   routes:
      desc: Generate routes for the front end
      cmds:
         - php artisan wayfinder:generate --path=../frontend/web/src/router

   format:
      desc: Formats application code with Pint
      cmds:
         - pint

   install:
      desc: Install all the packages for the application
      cmds:
         - rm -Rf vendor composer.lock
         - composer install

   lint:
      disc: Runs PHPStan over backend
      cmds:
         - ./vendor/bin/phpstan analyse --memory-limit=2G

   list:
      disc: Runs artisan route list but excludes vendor routes
      cmds:
         - php artisan route:list --except-vendor

   migrate:
      desc: Run database migrations
      cmds:
         - php artisan migrate

   run:
      cmds:
         - php artisan {{.CLI_ARGS}}

   seed:
      desc: Run database seeders
      cmds:
         - php artisan db:seed

   test:
      desc: Run all the tests
      cmds:
         - php artisan test --parallel

   update:
      desc: Update laravel dependencies
      cmds:
         - composer update
