version: "3"

tasks:
  clean:
    desc: Flush all the dependencies
    cmds:
      - rm -Rf vendor

  dump:
    desc: A composer dump
    cmds:
      - composer du

  format:
    desc: Formats application code with Pint
    cmds:
      - pint

  install:
    desc: Install all the packages for the application
    cmds:
      - composer install

  lint:
    disc: Runs PHPStan over backend
    cmds:
      - ./vendor/bin/phpstan analyse --memory-limit=2G

  migrate:
    desc: Run database migrations
    cmds:
      - php artisan migrate

  run:
    cmds:
      - php artisan {{.CLI_ARGS}}

  seed:
    desc: Run database seeders
    cmds:
      - php artisan db:seed

  test:
    desc: Run all the tests
    cmds:
      - php artisan test --parallel

  update:
    desc: Update laravel dependencies
    cmds:
      - composer update
