version: "3"

tasks:
   start:
      cmds:
         - pnpm dev:watch

   clear:
      cmds:
         - rm -Rf dist blank/dist web/dist

   install:
      cmds:
         - rm -Rf node_modules pnpm-lock.yaml web/node_modules web/pnpm-lock.yaml web/dist
         - pnpm install --recursive

   clean:
      cmds:
         - rm -Rf node_modules pnpm-lock.yaml dist blank/node_modules blank/pnpm-lock.yaml blank/dist web/node_modules web/pnpm-lock.yaml web/dist

   lint:
      cmds:
         - pnpm run lint

   format:
      cmds:
         - pnpm run format

   test:
      cmds:
         - pnpm --filter=@platform/blank test:unit

   update:
      desc: Update all dependencies
      cmds:
         - pnpm up -r --latest
