version: "3"

tasks:
  install:
    desc: Install frontend packages
    cmds:
      - pnpm i -r

  clean:
    desc: Flush all builds and node_modules
    cmds:
      - rm -Rf node_modules

  update:
    desc: Update all dependencies for all frontend projects
    cmds:
      - pnpm up -r --latest

  format:
    desc: Runs prettier over design and web
    cmds:
      - pnpm run format

  lint:
    desc: Runs ESLint over design and web
    cmds:
      - pnpm run lint
