version: "3"

ds:
  taskfile: ds.yml
  dir: ./frontend/ds

web:
  taskfile: web.yml
  dir: ./frontend/web

tasks:
  check:
    desc: Run Svelte Check TS
    cmds:
      - pnpm --filter=@platform/web run check
      - pnpm --filter=@platform/ds run check

  clean:
    desc: Clean all the frontend projects
    cmds:
      - rm -Rf node_modules
      - ds:clean
      - web:clean

  format:
    desc: Runs prettier
    cmds:
      - pnpm run format

  install:
    desc: Install frontend packages
    cmds:
      - pnpm i -r

  lint:
    desc: Runs ESLint
    cmds:
      - pnpm run lint

  test:
    desc: Runs tests
    cmds:
      - echo "run front test"

  update:
    desc: Update all dependencies
    cmds:
      - pnpm up -r --latest
