version: "3"

tasks:
   clear:
      cmds:
         - rm -Rf dist ds/dist web/dist

   clean:
      cmds:
         - rm -Rf node_modules pnpm-lock.yaml dist ds/node_modules ds/pnpm-lock.yaml ds/dist web/node_modules web/pnpm-lock.yaml web/dist

   lint:
      cmds:
         - pnpm run lint

   format:
      cmds:
         - pnpm run format

   test:
      cmds:
         - pnpm --filter=@platform/ds test:unit

   update:
      desc: Update all dependencies
      cmds:
         - pnpm up -r --latest
