version: "3"

tasks:
  purge:
    desc: Stop all docker containers and nuke them
    cmds:
      - task: stop
      - spin prune

  start:
    desc: Start docker
    cmds:
      - spin up --build --detach

  stop:
    desc: Stop the container
    cmds:
      - spin down

  env:
    desc: Generate an updated .env file
    cmds:
      - rm -rf application/.env .env
      - cat docker.env >> ../.env
      - cat docker.env app.env >> .env
