version: "3"

tasks:
   purge:
      desc: Stop all docker containers and nuke them
      cmds:
         - task: stop
         - spin prune

   start:
      desc: Start docker
      cmds:
         - spin up --build --detach

   start-nodetach:
      desc: Start docker without detaching it
      cmds:
         - spin up --build

   stop:
      desc: Stop the container
      cmds:
         - spin down

   restart:
      desc: Stop and restart all containers
      cmds:
         - task: stop
         - task: start

   refresh:
      desc: Stop, clear containers and start the container back up
      cmds:
         - task: purge
         - task: start
