<?php declare(strict_types=1);

// all paths are relative to the modules/module_name folder
return [
    'rootNamespace' => 'Platform',
    'moduleFolderName' => 'modules',
    'srcFolderName' => 'src',
    'namespaces' => [
        'casts' => '\Domain\Casts',
        'channel' => 'Application\Channels',
        'command' => '\Presentation\Console',
        'config' => '',
        'controller' => '\Presentation\Controllers',
        'event' => '\Application\Events',
        'exception' => '\Infrastructure\Exceptions',
        'factory' => 'database\factories',
        'job' => '\Application\Jobs',
        'listener' => '\Application\Listeners',
        'mail' => 'resources\email',
        'middleware' => '\Presentation\Middleware',
        'migration' => 'database\migrations',
        'model' => '\Domain\Models',
        'notification' => '\Application\Notifications',
        'observer' => '\Domain\Observers',
        'policy' => '\Infrastructure\Policies',
        'provider' => '\Infrastructure\Providers',
        'request' => '\Infrastructure\Requests',
        'resource' => '\Infrastructure\Resources',
        'route' => '',
        'rule' => '\Infrastructure\Rules',
        'scope' => '\Domain\QueryBuilders',
        'seeder' => 'database\Seeders',
        'test_feature' => '\Tests\Feature',
        'test_unit' => '\Tests\Unit',
    ],
    'files' => [
        'composer' => 'composer.json',
        'routes' => '{{module}}.routes.php',
        'config' => '{{module}}.config.php',
    ],
    'structure' => [
        'database' => [
            'factories' => [],
            'migrations' => [],
            'seeders' => [],
        ],
        'resources' => [
            'mail' => [],
            'views' => [],
        ],
        'tests' => [
            'Feature' => [],
            'Unit' => [],
        ],
        '{{src}}' => [
            'Application' => [
                'Actions' => [],
                'Jobs' => [],
                'Events' => [],
                'Listeners' => [],
                'Channels' => [],
                'Notification' => [],
            ],
            'Domain' => [
                'Casts' => [],
                'Collections' => [],
                'DataObjects' => [],
                'Models' => [],
                'Observers' => [],
                'QueryBuilders' => [],
                'ValueObjects' => [],
            ],
            'Infrastructure' => [
                'Exceptions' => [],
                'Policies' => [],
                'Providers' => [],
                'Requests' => [],
                'Resources' => [],
                'Rules' => [],
            ],
            'Presentation' => [
                'Console' => [],
                'Controllers' => [],
                'Middleware' => [],
            ],
        ],
    ],
];
