<?php declare(strict_types=1);

return [
    'root_namespace' => env('MODULE_NAMESPACE', 'Platform'),
    'module_folder' => env('MODULE_FOLDER', 'modules'),
    'src_folder' => env('MODULE_SRC', 'src'),
    'namespaces' => [
        'actions' => '\Domain\Actions',
        'casts' => '\Domain\Casts',
        'channel' => '\Channels',
        'collection' => '\Domain\Collections',
        'command' => '\Presentation\Console\Commands',
        'config' => 'config',
        'controller' => '\Presentation\Http\Controllers',
        'data_objects' => '\DataObjects',
        'event' => '\Domain\Events',
        'exception' => '\Exceptions',
        'factory' => '\Database\Factories',
        'job' => '\Services\Jobs',
        'listener' => '\Services\Listeners',
        'mail' => 'resources/email',
        'middleware' => '\Presentation\Http\Middleware',
        'migration' => 'database/migrations',
        'model' => '\Domain\Models',
        'notification' => '\Services\Notifications',
        'observer' => '\Domain\Observers',
        'policy' => '\Domain\Policies',
        'provider' => '\Providers',
        'queries' => '\Domain\Queries',
        'repositories' => '\Contracts',
        'request' => '\Presentation\Http\Requests',
        'resource' => '\Presentation\Resources',
        'route' => 'routes',
        'rule' => '\Domain\Rules',
        'scope' => '\Domain\Builders',
        'seeder' => '\Database\Seeders',
        'services' => '\Services',
        'test_feature' => '\Tests\Feature',
        'test_unit' => '\Tests\Unit',
        'value_objects' => '\Domain\ValueObjects',
    ],
    'files' => [
        'composer' => 'composer.json',
    ],
    'structure' => [
        'config' => [],
        'database' => [
            'factories' => [],
            'migrations' => [
                'tenant' => [],
            ],
            'seeders' => [],
        ],
        'resources' => [
            'mail' => [],
        ],
        'routes' => [],
        'tests' => [
            'Feature' => [],
            'Unit' => [],
        ],
        'src' => [
            'Contracts' => [],
            'DataObjects' => [],
            'Domain' => [
                'Actions' => [],
                'Collections' => [],
                'Models' => [],
                'Queries' => [],
                'Repositories' => [],
                'ValueObjects' => [],
            ],
            'Presentation' => [
                'Http' => [
                    'Controllers' => [],
                    'Middleware' => [],
                    'Requests' => [],
                ],
                'Console' => [],
            ],
            'Services' => [],
        ],
    ],
];
