name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    # types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Configure release tag
        run: echo "release_tag=$(date +'v%Y.%m.%d.%H%M%S') >> $GITHUB_ENV"

      - name: Draft the release
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{env.release_tag}}
          version: ${{ env.release_tag}}
          disable-autolabeler: true
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
